### ISSUE TITLE
Hunger

### ISSUE THREAD

**Issue by black-roselp** [vorburger/minecraft-storeys-maker#62]
Right now you can't build anything, but you do get hungry so you'll die.

**Comment by vorburger** [comment]
@black-roselp FYI @devvorb explained to me that setting the [difficulty](https://minecraft.gamepedia.com/Difficulty) to 0 for Peaceful [instead of our current 1 for Easy](https://minecraft.gamepedia.com/Server.properties) will let you never be hungry. Apparently this will also prevent mobs from spawning at night and in the dark (which I guess if good, for a creative server), but perhaps also prevent us from manually spawning mobs for stories - which perhaps we want to revisit, later. (@devvorb said that for that, we could reset the difficulty to 1, or even more, and then give players some sort of a potion so that they are never hungry.)

I've just merged https://github.com/OASIS-learn-study/s2i-minecraft-server/pull/6 and this will be live on the server in a few minutes from now (CI/CD is currently rebuilding and redeploying all of it) - do you then want to test if it works as you expect, and if it does then close this issue as Done?
